<a href="https://colab.research.google.com/github/pshemach/Computer-Vision/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
tensor1 = torch.tensor(8)
tensor1

tensor(8)

In [3]:
tensor1.dtype

torch.int64

In [4]:
tensor2 = torch.tensor([10,20,30,40])
print(tensor2)
print(tensor2.dtype)

tensor([10, 20, 30, 40])
torch.int64


In [5]:
tensor2 = torch.tensor([10,20.0,30,40])
print(tensor2)
print(tensor2.dtype)

tensor([10., 20., 30., 40.])
torch.float32


In [6]:
tensor2d = torch.tensor([[12.0,2],[45,2],[3,2],[0,87]])
print(tensor2d)
print(tensor2d.dtype)

tensor([[12.,  2.],
        [45.,  2.],
        [ 3.,  2.],
        [ 0., 87.]])
torch.float32


In [7]:
tensor3d = torch.tensor([
    [[1,2,3],[4,5,6]],
    [[10,20,30],[40,50,60]]
])

print(tensor3d)
print(tensor3d.dtype)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[10, 20, 30],
         [40, 50, 60]]])
torch.int64


In [8]:
stream_list = ['netflix','hulu','prime video','hbo max']

from sklearn import preprocessing
stringEncoder = preprocessing.LabelEncoder()
targets = stringEncoder.fit_transform(stream_list)
tensorList = torch.as_tensor(targets)
print(tensorList)
print(tensorList.dtype)

tensor([2, 1, 3, 0])
torch.int64


In [12]:
print(tensor1)
print(f'Shape {tensor1.shape}\n')
print(tensor2)
print(f'Shape {tensor2.shape}\n')
print(tensor2d)
print(f'Shape {tensor2d.shape}\n')
print(tensor3d)
print(f'Shape {tensor3d.shape}\n')
print(tensorList)
print(f'Shape {tensorList.shape}\n')

tensor(8)
Shape torch.Size([])

tensor([10., 20., 30., 40.])
Shape torch.Size([4])

tensor([[12.,  2.],
        [45.,  2.],
        [ 3.,  2.],
        [ 0., 87.]])
Shape torch.Size([4, 2])

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[10, 20, 30],
         [40, 50, 60]]])
Shape torch.Size([2, 2, 3])

tensor([2, 1, 3, 0])
Shape torch.Size([4])



In [13]:
#y = mx + c

x = torch.tensor(5.)
m = torch.tensor(10., requires_grad=True)
c = torch.tensor(20., requires_grad=True)

In [14]:
y = m*x + c
y

tensor(70., grad_fn=<AddBackward0>)

In [15]:
y.backward()

In [16]:
print("dy/dx", x.grad)
print("dy/dm", m.grad)
print("dy/dc", c.grad)

dy/dx None
dy/dm tensor(5.)
dy/dc tensor(1.)


In [17]:
tensor1 = torch.full((3,2), 20)

In [18]:
tensor1

tensor([[20, 20],
        [20, 20],
        [20, 20]])

In [19]:
tensor2 = torch.tensor([[20,32],[72,85],[78,30]])
print(tensor2)

tensor([[20, 32],
        [72, 85],
        [78, 30]])


In [20]:
#concatination

tensorConcat = torch.cat((tensor1,tensor2))

In [21]:
print(tensorConcat)

tensor([[20, 20],
        [20, 20],
        [20, 20],
        [20, 32],
        [72, 85],
        [78, 30]])
